class Status:
    OK = "OK"
    PROMPT = "> "
    TIMEOUT = "TIMEOUT"
    ERROR_SIM_PUK = "ERORR_SIM_PUK"
    ERROR_SIM_NOT_INSERTED = "ERROR_SIM_NOT_INSERTED"
    ERROR = "ERROR"
    UNKNOWN = "UNKNOWN"
